apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-service
  namespace: shortly
  labels:
    app: redirect-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redirect-service
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      containers:
        - name: redirect-service
          image: redirect-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: shortly-config
            - secretRef:
                name: shortly-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
