apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: shortly
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: LINK_SERVICE_URL
              value: "http://link-service:8001"
            - name: REDIRECT_SERVICE_URL
              value: "http://redirect-service:8002"
          envFrom:
            - configMapRef:
                name: shortly-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
